baseurl = "/"
languageCode = "en-us"
theme = "typo"
title = "A journey into a wild pointer"

[params]
    homeIntroTitle = ""
    homeIntroContent = ""
    colorPalette = "eink"
    faviconPath = "favicons"
    theme = "auto"
    homeCollectionTitle = "posts"
    homeCollection = "posts"
    showFooter = true
    paginationSize = 15
    listDateFormat = '2 Jan 2006'
    listSummaries = false
    showTags = false

[[params.menu]]
    name = "posts"
    url = "/posts"

[[params.menu]]
    name = "projects"
    url = "/projects"

[[params.menu]]
    name = "blame"
    url = "/blame"

[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/k0pernicus"

[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://linkedin.com/in/antonin-carette-792bbb82"

[[params.social]]
    name = "rss"
    icon = "rss"
    url = "/index.xml"

[params.breadcrumbs]
    enabled = true
    showCurrentPage = true
    home = "~"

[permalinks]
    post = "/:year/:month/:day/:filename/"

[markup]
    [markup.highlight]
        style = 'algol'
